#!/bin/bash
CreateFiles(){
  mkdir "$1/build"
  touch "$1/CMakeLists.txt"
  mkdir "$1/src"
  git init
}
New(){
  mkdir $1
  if [ $? = 0 ]
  then
    CreateFiles $1
  fi
}
Make(){
  cmake ./
  if [ $? = 0 ]
  then
    make -C build
  fi
}
Init(){
  CreateFiles .
}
Help(){
  echo
  echo "new <project_name> : creates a new project with name <project_name>"
  echo "make               : uses cmake to build the project"
  echo
}

case $1 in
  new)
    New $2
    ;;
  make)
    Make
    ;;
  init)
    Init
    ;;
  help)
    Help
    ;;
  *)
    echo "command not recognised, 'cqute help' for a list of options" 
    ;;
esac
